# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  timeout: 5000
  username: TR
  password: TR

test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  pool: 5
  timeout: 5000
  username: TR
  password: TR

production:
  adapter: postgresql
  encoding: unicode
  database: my_database_production
  pool: 5
  timeout: 5000
  username: TR
  password: TR
