# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba75b05bbbcd99cb5b56743775eb399a390fefcd3260b39e2c592f823d8f1cfa6367cd4fa7b01ddf3b6cead596a8e0e1619dd2c7400934b0a316c3473d8f044

test:
  secret_key_base: 21b4532458bae7eb8154775dfa2dd3145991a31f8d4a4779f7947497e8a054835e794523e2d50da917e53fca26c9d51c988bf52b1da008ed2c8d016711469d04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
